{{- $fullName := include "hub-enterprise.fullname"  . -}}
{{- if eq .Values.hubEnterprise.ingress.type "nginx" -}}
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
  annotations:
    timestamp: {{ date "20060102150405" now | quote }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hubEnterprise.hostname }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.hubEnterprise.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  name: http
{{- else if eq .Values.hubEnterprise.ingress.type "contour" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
  annotations:
    projectcontour.io/websocket-routes: "/"
spec:
  rules:
  - host: {{ .Values.hubEnterprise.hostname }}
    http:
      paths:
      - path: /
        pathType: {{ .Values.hubEnterprise.ingress.pathType }}
        backend:
          service:
            name: {{ $fullName }}
            port: 
              name: http
  tls:
  - hosts:
    - {{ .Values.hubEnterprise.hostname }}
    secretName: {{ .Values.hubEnterprise.ingress.secretName }}
{{- else if eq .Values.hubEnterprise.ingress.type "openshift" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: {{ $fullName }}
  name: {{ $fullName }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $fullName }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
