apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-enterprise.fullname" . }}-db-migration-job
data:
   JAEGER_SERVICE_NAME: {{ .Values.dbData.JAEGER_SERVICE_NAME | b64enc }}
{{ range $key, $value := .Values.dbData }}
   {{ $key }}: {{ $value | b64enc }}
{{ end }}
