{{- if .Values.monitoring.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "hub-enterprise.fullname" . }}-grafana-loki-ds"
  annotations:
    timestamp: {{ date "20060102150405" now | quote }}
data:
{{- range $path, $config := .Values.grafana.loki }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
