apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hub-service-1
  name: hub-service-1
  namespace: openlegacy-service
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hub-service-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hub-service-1
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: hub-service-1-secrets
        image: harbor-01.ipa-bs.org/openlegacy/main-frame-rpc-spring-java-rest:3.0.9
        imagePullPolicy: IfNotPresent
        name: hub-service-1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/opz
          name: metadata-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: metadata-volume
        persistentVolumeClaim:
          claimName: hub-service-1-pvc
 