apiVersion: v1
kind: Secret
metadata:
  name: hub-service-1-secrets
  namespace: openlegacy-service
type: Opaque
stringData:
  OL_FLOW_TYPE: RPC
  OL_SOURCE_PROVIDER: OL_PROJECT_ZIP
  OL_PROJECT_ZIP_PATH: /usr/opz/ol-project.opz
  OL_LICENSE_KEY: eyJhbGciOiJSUzI1NiJ9.eyJtYXN0ZXJMaWNlbnNlSWQiOiJhZDAyODQwMC0xZWMyLTRiY2YtOWFmNC1mNjE2MzQ1ZTZhMmMiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjgtMDQtMzBUMjE6MDA6MDBaIiwiaXNzdWVEYXRlIjoiMjAyNS0wNC0yMlQxMjozNToxMC44NDM0NDI5ODFaIiwidGVuYW50SWQiOiIyNGNjOTcwNi1mNzY3LTQzZTItODZiOS04YmYyNDA2Yjk0OGYiLCJncmFjZVBlcmlvZERheXMiOjkwLCJsaWNlbnNlVHlwZSI6IkRFVkVMT1BNRU5UIn0.tTGV6itg1-axcYigDYkHh7Kvdv1lojzuYgVk9CDOdXKVHPBUl8i-JlLqMGBuYG1dvxNZsCCKq4fCOtJjwd5GjGLSVZHDjXeiumPaXvOJAVwPonRdDr74u_GjElUJrZS4h7s0s_xrwmA-k0LhV1yQYBWIM_6vd3RCSmjZUwHcCaU7gBvqc_VnJMcaDZxD7ZNLePbKZ0mV7v7l6p7Zpq_3xX66jla12z7_NHchJasRgvIQqmZgNK6aC1eLGjmL5Rc4UdEh0tONpDPAy5gmmZ1P_G-mz2E8AQaQhqvaEJxfaTF8GAkQYJBbMvL8-WOsJjopicfRhMOMMhnSrPU0ayLgBg

