apiVersion: v1
kind: Service
metadata:
  name: hub-service-1
  namespace: openlegacy-service
spec:
  selector:
    app: hub-service-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP