apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hub-ent
  namespace: default
spec:
  virtualhost:
    fqdn: hub-ent.local
  routes:
    - services:
        - name: hub-ent
          port: 80
      conditions:
        - prefix: / 