{{- if .Values.monitoring.deploy }}
{{- $fullName := (list (include "hub-enterprise.fullname" .) "loki" | join "-") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ include "hub-enterprise.fullname" . }}
  name: {{ $fullName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.storage.size }}
{{- end -}}
