{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-enterprise.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
