apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-enterprise.fullname" . }}
  annotations:
     timestamp: {{ date "20060102150405" now | quote }}
data:
{{- if not .Values.hubEnterprise.env.AUTH_DOMAIN }}
   AUTH_DOMAIN: {{ include "hub-enterprise.keycloakURL" . }}
{{- end -}}
{{- if not .Values.hubEnterprise.env.OL_HUB_URL }}
   OL_HUB_URL: {{ include "hub-enterprise.hubURL" . }}
{{- end -}}
{{- if not .Values.hubEnterprise.env.HUB_IAM_URL }}
   HUB_IAM_URL: {{ include "hub-enterprise.hubIamUrl" . }}
{{- end -}}
{{- if not .Values.hubEnterprise.env.BACKOFFICE_IAM_URL }}
   BACKOFFICE_IAM_URL: {{ include "hub-enterprise.backofficeIamUrl" . }}
{{- end -}}
{{- if not .Values.hubEnterprise.env.KEYCLOAK_BASE_URL }}
   KEYCLOAK_BASE_URL: {{ include "hub-enterprise.keycloakBaseURL" . }}
{{- end -}}
{{- if .Values.hubEnterprise.OL_SCREEN_PORT }}
   OL_SCREEN_PORT: {{ .Values.hubEnterprise.OL_SCREEN_PORT | b64enc }}
{{- end -}}
{{ range $key, $value := .Values.dbData }}
   {{ $key }}: {{ $value | b64enc }}
{{ end }}
{{ range $key, $value := .Values.hubEnterprise.env }}
   {{ $key }}: {{ $value | b64enc }}
{{- end -}}
