{{- if .Values.monitoring.deploy }}
{{- $fullName := (list (include "hub-enterprise.fullname" .) "grafana" | join "-") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hub-enterprise.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hub-enterprise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: {{ date "20060102150405" now | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ $fullName }}
        {{- include "hub-enterprise.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "hub-enterprise.fullname" . }}-pull-secret
      serviceAccountName: {{ include "hub-enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.grafana.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 90
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $fullName }}
              mountPath: {{ .Values.grafana.storage.mountPath }}
            - name: "{{ $fullName }}-loki-ds"
              mountPath: /etc/grafana/provisioning/datasources/loki.yaml
              subPath: loki.yaml
            - name: "{{ $fullName }}-prometheus-ds"
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
              subPath: prometheus.yaml
      volumes:
        - name: {{ $fullName }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}
        - name: "{{ $fullName }}-loki-ds"
          configMap:
            name: "{{ $fullName }}-loki-ds"
        - name: "{{ $fullName }}-prometheus-ds"
          configMap:
            name: "{{ $fullName }}-prometheus-ds"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
