apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hub-enterprise.fullname" . }}-keycloak
  annotations:
     timestamp: {{ date "20060102150405" now | quote }}
data:
   DB_PASSWORD: {{ .Values.dbData.OL_DB_PASSWORD | b64enc }}
   DB_USER: {{ .Values.dbData.OL_DB_USER | b64enc }}
{{ range $key, $value := .Values.keycloak.env }}
   {{ $key }}: {{ $value | b64enc }}
{{ end }}
