apiVersion: v1
kind: Secret
metadata:
  name: hub-enterprise-postgres
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "1"
  #   "helm.sh/resource-policy": keep
data:
   POSTGRES_PASSWORD: {{ .Values.dbData.OL_DB_PASSWORD | b64enc }}
   POSTGRES_USER: {{ .Values.dbData.OL_DB_USER | b64enc }}
   DB_PORT: {{ .Values.dbData.OL_DB_PORT | b64enc }}
   PGDATA: {{ "/var/lib/postgresql/data/pgdata" | b64enc }}
