{{- if .Values.postgres.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hub-enterprise-postgres
  name: hub-enterprise-postgres
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "1"
  #   "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
