{{- if .Values.postgres.deploy }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hub-enterprise-postgres
    provider: fabric8
  name: hub-enterprise-postgres
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "1"
  #   "helm.sh/resource-policy": keep
spec:
  ports:
    - name: http
      port: {{ .Values.dbData.OL_DB_PORT }}
      protocol: TCP
      targetPort: 5432
  selector:
    app: hub-enterprise-postgres
    tier: database
{{- end }}
